### ISSUE TITLE
Add a countdown timer

### ISSUE THREAD

**Issue by gpitfield** [gpitfield/replay#2]
A little JS thingy to that updates and says something like "Tournament starts in 7 minutes"

**Comment by gpitfield** [comment]
Tournament data can be pulled from https://matchplay.events/data/tournaments/tournament_id and we can pass in the tournament id as a query param. That endpoint includes start time info, as well as a list of players so we could show a player count.

**Comment by churfzilla** [comment]
# #4

Here is the JS for the timer for now, I'll expand on this later today.

**Comment by gpitfield** [comment]
Shipped!
